version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tictactoe-api
    restart: unless-stopped
    ports:
      - "3021:3021"
    environment:
      - NODE_ENV=production
      - PORT=3021
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - tictactoe-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3021/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:alpine
    container_name: tictactoe-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deployment/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro
    depends_on:
      - api
    networks:
      - tictactoe-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  tictactoe-network:
    driver: bridge
